CONFIG_DIRECTORY = "/opt/project/test_config"
TEST_DATA_API_DIRECTORY = "/opt/project/test_data/api"
TEST_DATA_DB_DIRECTORY = "/opt/project/test_data/db"
TEST_DATA_WEB_UI_DIRECTORY = "/opt/project/test_data/web_ui"
LOGS_DIRECTORY = "/opt/project/test_logs"
